menu:
  Mis propuestas:
    Sesiones Individuales: /acompanamiento-creativo.html
    'Sesiones Grupales: "Escuchándonos"': /talleres-sobre-comunicacion.html
    Talleres de Movimiento Expresivo: /talleres-de-movimiento.html
    Sesiones de Masaje: /sesiones-individuales-de-masaje.html
  'Libro: "la corazón"': /libro-la-corazon.html
  Agenda: /agenda.html
  Más información:
    Trayectoria: /mas-informacion.html
    Movimiento y conciencia corporal: /copia-de-conciencia-corporal.html
    Sistema Río Abierto: /sistema-rio-abierto.html
  Escritos:
    Recordar quiénes somos: /recordar-quienes-somos.html
    Había una vez ...: /habia-una-vez.html
    Pensar y sentir: /pensar-y-sentir.html
    Conciencia: /conciencia.html
  Contacto: /contacto.html
fancybox: false
